name: base-python-fastapi-build

env:
  TITLE: base-python-fastapi
  BASE_VERSION: 3.8

on:
  push:
    paths:
      - 'base-python-fastapi/3.8/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to myhuaweicloud-swr
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOMESTIC_DOCKER_SERVER }}
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          file: base-python-fastapi/3.8/Dockerfile
          push: true
          tags: ${{ secrets.DOMESTIC_DOCKER_SERVER }}/wutong/${{ env.TITLE }}:${{ env.BASE_VERSION }}        